### ISSUE TITLE
パパッとviewを作る

### ISSUE THREAD

**Issue by acculief** [jphacks/TK_1801#8]
## what
Bootstrapでviewの型をざっくり作る
ルーティングとかの細かい仕様は後ほど擦り合わせようと思います

**Comment by acculief** [comment]
とりまヘッダーとフッターと新規登録画面をざっくり実装

**Comment by acculief** [comment]
残り必要なview
・お知らせ画面
・マッチ認証画面（案内側だけ。観光側にはお知らせが届く)

**Comment by nakarin0528** [comment]
パパッとDone
